// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Api.DataLayer;

#nullable disable

namespace StarWars.Api.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    partial class StarWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("StarWars.Api.DataLayer.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthYearBBY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<float>("HeightMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginPlanetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41150197-125a-46af-b160-8b191d3fbf93"),
                            BirthYearBBY = 42,
                            Description = "Служил Галактической Республике как рыцарь-джедай, позже служил Галактической Империи и командовавший её войсками, как Лорд ситхов Дарт Вейдер. Рождённый Шми Скайуокер, в юности стал тайным мужем сенатора с Набу, Падме Амидалы Наберри. Он был отцом гранд-мастера Люка Скайуокера, рыцаря-джедая Леи Органы-Соло и дедом Бена Скайуокера. Хотя, будучи взрослым, Энакин стал ключевой фигурой в Галактике, не смотря на низкое происхождение. Первые годы своей жизни он провёл на Татуине вместе со своей матерью в качестве раба.",
                            EyeColor = "Голубой",
                            Gender = 0,
                            HairColor = "Русый",
                            HeightMeters = 1.88f,
                            Name = "Энакин Скайуокер",
                            OriginPlanetName = "Татуин",
                            OriginalName = "Anakin Skywalker",
                            Race = "Человек"
                        },
                        new
                        {
                            Id = new Guid("bbdc11bf-e583-4314-ab17-29782e804557"),
                            BirthYearBBY = 82,
                            Description = "Могущественный тёмный лорд ситхов, который, благодаря собственной хитрости и интригам сделал себе головокружительную политическую карьеру, став, в конечном итоге, последним Верховным канцлером Республики и первым императором Галактической Империи. Это был, пожалуй, один из наиболее могущественнейших, если, не самый могущественный, адепт Тёмной стороны, обладавший поистине колоссальной мощью: его не смогли убить ни Мейс Винду, ни Йода, ни Гален Марек ни многие, многие другие джедаи и противники. Он был тёмным лордом ситхов, который придерживался Правила двух, правила Ордена лордов ситхов и был самым успешным и влиятельным ситхом, которого когда-либо знала Галактика, сумевшим воплотить в жизнь Великий план и уничтожить как Орден джедаев, так и саму Республику, став единоличным и безоговорочным повелителем всей Галактики. ",
                            EyeColor = "Голубой",
                            Gender = 0,
                            HairColor = "Рыжий",
                            HeightMeters = 1.73f,
                            Name = "Палпатин",
                            OriginPlanetName = "Набу",
                            OriginalName = "Palpatine",
                            Race = "Человек"
                        });
                });

            modelBuilder.Entity("StarWars.Api.DataLayer.Entities.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = new Guid("720733c0-8327-40aa-ba24-0ee67c273fe1"),
                            Name = "Звёздные войны. Эпизод I: Скрытая угроза",
                            ReleaseDate = new DateTime(1999, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1f90431e-2189-464f-944d-0258da70deb6"),
                            Name = "Звёздные войны. Эпизод II: Атака клонов",
                            ReleaseDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6f68aca3-0ce7-4cdd-9c0c-cc097aa42ad5"),
                            Name = "Звёздные войны. Эпизод 3: Месть ситхов",
                            ReleaseDate = new DateTime(2020, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("34c4ac65-be5e-4bd6-86c3-06f4a7598253"),
                            Name = "Звёздные войны: Пробуждение Силы",
                            ReleaseDate = new DateTime(2015, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc33071f-7241-4594-9d6c-2b58afdc5f31"),
                            Name = "Изгой-один: Звёздные войны. Истории",
                            ReleaseDate = new DateTime(2016, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7b1e26ed-2548-4e3f-ae5d-6610c69dd3cf"),
                            Name = "Звёздные войны: Последние джедаи",
                            ReleaseDate = new DateTime(2017, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("899573e9-8bb6-492f-806e-fa48d23b58e3"),
                            Name = "Хан Соло: Звёздные Войны. Истории",
                            ReleaseDate = new DateTime(2018, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("73aadd9f-821c-4720-97eb-edf5b597f7b7"),
                            Name = "Звёздные войны: Скайуокер. Восход",
                            ReleaseDate = new DateTime(2019, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StarWars.Api.DataLayer.Entities.FilmCharacterLink", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("FilmId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("CharacterId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmCharacterLink");

                    b.HasData(
                        new
                        {
                            CharacterId = new Guid("bbdc11bf-e583-4314-ab17-29782e804557"),
                            FilmId = new Guid("720733c0-8327-40aa-ba24-0ee67c273fe1")
                        },
                        new
                        {
                            CharacterId = new Guid("bbdc11bf-e583-4314-ab17-29782e804557"),
                            FilmId = new Guid("1f90431e-2189-464f-944d-0258da70deb6")
                        },
                        new
                        {
                            CharacterId = new Guid("bbdc11bf-e583-4314-ab17-29782e804557"),
                            FilmId = new Guid("6f68aca3-0ce7-4cdd-9c0c-cc097aa42ad5")
                        },
                        new
                        {
                            CharacterId = new Guid("41150197-125a-46af-b160-8b191d3fbf93"),
                            FilmId = new Guid("720733c0-8327-40aa-ba24-0ee67c273fe1")
                        },
                        new
                        {
                            CharacterId = new Guid("41150197-125a-46af-b160-8b191d3fbf93"),
                            FilmId = new Guid("1f90431e-2189-464f-944d-0258da70deb6")
                        },
                        new
                        {
                            CharacterId = new Guid("41150197-125a-46af-b160-8b191d3fbf93"),
                            FilmId = new Guid("6f68aca3-0ce7-4cdd-9c0c-cc097aa42ad5")
                        });
                });

            modelBuilder.Entity("StarWars.Api.DataLayer.Entities.FilmCharacterLink", b =>
                {
                    b.HasOne("StarWars.Api.DataLayer.Entities.Character", null)
                        .WithMany("FilmLinks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Api.DataLayer.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("StarWars.Api.DataLayer.Entities.Character", b =>
                {
                    b.Navigation("FilmLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
